#!/bin/bash

#SBATCH --partition=batch
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=3072
#SBATCH --time=60:00
#SBATCH --output=outfile-%J
#SBATCH --gpus=8
#SBATCH --container-image=ubuntu 
#SBATCH --container-mounts=/data:/data 
#set -x

srun --container-image ubuntu --container-mounts /data:/data /data/setenv-spark-gpu.sh \

$SPARK_HOME/sbin/start-all.sh \
/data/wait-worker.sh

echo "test complete"
#sleep infinity
$SPARK_HOME/sbin/stop-all.sh
